# Generated by Django 5.1.2 on 2024-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'table1',
            },
        ),
    ]
