# Generated by Django 5.1.2 on 2024-11-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_table1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
        migrations.AlterModelTable(
            name='user',
            table='table1',
        ),
    ]
