# Generated by Django 5.1.2 on 2024-11-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_delete_table1_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
