# Generated by Django 5.1.2 on 2024-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=1, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phoneNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'Team',
            },
        ),
    ]
