# Generated by Django 5.1.2 on 2024-11-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
