# Generated by Django 5.1.2 on 2024-11-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_profile_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
