# Generated by Django 5.1.2 on 2024-11-29 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_remove_profile_user_delete_room_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


