# Generated by Django 5.1.2 on 2024-11-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
