# Generated by Django 5.1.2 on 2024-11-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_delete_room'),
    ]
