# Generated by Django 5.1.2 on 2024-11-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='DefaultFirst', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='DefaultLast', max_length=30),
        ),
    ]
