# Generated by Django 5.1.2 on 2024-12-02 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('playground', '0014_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images')),
                ('bio', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(default='DefaultFirst', max_length=30)),
                ('last_name', models.CharField(default='DefaultLast', max_length=30)),
            ],
        ),
    ]
