# Generated by Django 5.0.4 on 2024-12-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_myprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
